<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_emergencyOtherNumber</name>
   <tag></tag>
   <elementGuidId>edcbc9c3-16b2-43c4-a2cb-697daf733f62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmergencyOtherNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyOtherNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58ebbf75-e2ee-4e72-875e-fb321f14cc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>0f824bd5-d8a9-4474-ad92-d7e4dba4a233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>e3c2db02-cd82-412d-8652-033a40c2c2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyOtherNumber</value>
      <webElementGuid>f7943ee5-a8e9-4ab5-8c4a-9acf5e141da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>+1 (234) 567-8910</value>
      <webElementGuid>a8a3cc1b-8e49-42c6-b8cc-347c18209a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyOtherNumber</value>
      <webElementGuid>53ec1e85-9ad4-47d4-86c6-c1fa75556ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyOtherNumber&quot;)</value>
      <webElementGuid>3ae61e99-a055-4cd2-aa3b-a71f1fab90b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmergencyOtherNumber']</value>
      <webElementGuid>29df4211-d037-43fa-ab7b-96c1638f0134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[6]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>763ee079-1053-45e1-8786-45cfa9fd4f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>17777ddb-69bf-4f20-a465-648e777cbc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'inputEmergencyOtherNumber' and @placeholder = '+1 (234) 567-8910' and @name = 'emergencyOtherNumber']</value>
      <webElementGuid>431a6424-6313-407a-a095-f89a8716dd95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
