<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_emergencyMobileNumber</name>
   <tag></tag>
   <elementGuidId>a08d04e5-b195-4c32-bc22-5cac191edc84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmergencyMobileNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyMobileNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>774f6258-4318-4ffa-85a1-3193f85c1002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3fa6c6d2-e1b6-43f2-bf30-e1123d636847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>2cd4e1bd-2821-4be8-8238-15619fff1379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyMobileNumber</value>
      <webElementGuid>afb6b8cd-4a54-4e4b-bb1f-ae04a98cdd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>+1 (234) 567-8910</value>
      <webElementGuid>5755a640-2a68-438d-97f7-f4aad940b97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyMobileNumber</value>
      <webElementGuid>9b9d610c-95d2-436e-a654-b11bb509d4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyMobileNumber&quot;)</value>
      <webElementGuid>b1e5d8c1-d278-44e1-9090-8573a3e79dab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmergencyMobileNumber']</value>
      <webElementGuid>4e7ed682-d240-40a8-9271-5ba7717a05a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>334440d2-1d0b-47fc-8edb-473b3226ff5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>99638583-8f7c-40b9-afcc-9ea0c3f13dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'inputEmergencyMobileNumber' and @placeholder = '+1 (234) 567-8910' and @name = 'emergencyMobileNumber']</value>
      <webElementGuid>261a5240-88c0-4c05-a44e-a3f7dcd09aa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
