<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_name</name>
   <tag></tag>
   <elementGuidId>868bfa11-4b1c-41cd-a9a8-415635cc568a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1595c4f5-24d3-4b33-bfe3-cf759b8a73ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input </value>
      <webElementGuid>10df1005-3a2e-4f0c-8ed9-2c9e123fc506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputname</value>
      <webElementGuid>5e2c9d44-046b-448c-87d3-7ad42fbec57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4989af4d-dbc6-44d6-99e6-65a37283068d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>8844cf38-f79b-400f-a5cb-7704b7770f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: Mark Johnson</value>
      <webElementGuid>157b8700-21ab-4c0a-876b-cbfa6ad25dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputname&quot;)</value>
      <webElementGuid>d686a31b-f802-42bc-9b4f-018e26ee5d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputname']</value>
      <webElementGuid>8768cbe8-eb3f-47a7-b6a1-91cb16355d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>4f19e5f0-bc39-4ac0-8fdb-adfce5dc7eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4c5b9833-fe14-480e-8c52-0b3eff4c9866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputname' and @type = 'text' and @name = 'name' and @placeholder = 'Example: Mark Johnson']</value>
      <webElementGuid>a64a5287-8583-4ea9-af40-b7103b593075</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
