<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_zipcode</name>
   <tag></tag>
   <elementGuidId>74bafb02-d154-4f13-8cc2-aa30266ebce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputzipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputzipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c1ff936-b4ec-4259-ba09-567c7eec25b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input </value>
      <webElementGuid>49c3daac-99ae-447d-812a-1b12f7a6c683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputzipcode</value>
      <webElementGuid>4628b1e1-f639-4327-8c56-070ef3e0f5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0e8efda-379d-4363-b184-c947d4e88664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>5bff7f82-edd9-4971-a96c-3296288eec18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter ZIP code of your location</value>
      <webElementGuid>2d4c23cb-890f-4275-b9cf-8cba98b09846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputzipcode&quot;)</value>
      <webElementGuid>50f9bd1d-b11d-4344-af08-f0e82c198ab3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputzipcode']</value>
      <webElementGuid>ca5ecfce-b239-4328-85da-59baa2c75137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div[2]/input</value>
      <webElementGuid>2e7b6327-8974-434a-a9f0-f8cae27ad644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1b4bee2f-a74f-4d82-b3d6-98e6342d66cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputzipcode' and @type = 'text' and @name = 'zipcode' and @placeholder = 'Enter ZIP code of your location']</value>
      <webElementGuid>590095ee-8ed3-4403-9c44-71b24ee73699</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
