<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_Shared_Purpose</name>
   <tag></tag>
   <elementGuidId>83205d3a-f120-4b13-80ba-3f3f8d945b4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.sub-header-heading-text.m-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>093ad9c3-d5a3-4503-bc24-a88d6233d802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-header-heading-text m-0</value>
      <webElementGuid>e44977cd-fdb8-4a7e-963e-6fb496841e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shared Purpose</value>
      <webElementGuid>ed3c3d3f-49b6-43f3-bd5f-d93c69e86924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container wrapper&quot;]/div[@class=&quot;main--container&quot;]/div[@class=&quot;row justify-content-between&quot;]/div[@class=&quot;col-12 col-md-6 read-card-container mx-auto mx-md-0 my-3 my-sm-0&quot;]/div[@class=&quot;row card-container-box&quot;]/div[@class=&quot;frame-33&quot;]/div[@class=&quot;div-2 row mx-auto&quot;]/div[@class=&quot;col-12 card-container p-0&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;sub-header&quot;]/div[@class=&quot;sub-header-heading&quot;]/p[@class=&quot;sub-header-heading-text m-0&quot;]</value>
      <webElementGuid>151fe99f-06cd-41cd-8d9e-fdca4ae60022</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div[2]/p</value>
      <webElementGuid>0e3ff984-d4bf-442e-86d4-181aaa535d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/p</value>
      <webElementGuid>95ff918d-36a7-46d7-8862-542a668e8d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Shared Purpose' or . = 'Shared Purpose')]</value>
      <webElementGuid>6b282585-ba57-485f-94d8-3e9dcbf87725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
