<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Need Help in calendar Weve got your back</name>
   <tag></tag>
   <elementGuidId>83b25344-6c0a-463a-aa22-d56e4a9797ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>43be51c1-0b70-4b58-9eb4-249f28cf72c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Need Help in calendar? We've got your back</value>
      <webElementGuid>5e021f2f-c96f-4a2e-b085-6dc2f1a6e6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;mt-2&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-md-7&quot;]/h3[1]</value>
      <webElementGuid>6415d8fe-644d-49f1-ad3d-441d624ccbb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/h3</value>
      <webElementGuid>0692e133-1371-4af9-9cdd-0f18690c4a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>bfcf90d3-f625-4dea-959c-a61f152b1cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = concat(&quot;Need Help in calendar? We&quot; , &quot;'&quot; , &quot;ve got your back&quot;) or . = concat(&quot;Need Help in calendar? We&quot; , &quot;'&quot; , &quot;ve got your back&quot;))]</value>
      <webElementGuid>17f53560-63fa-4e53-8914-dad64d2c383f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
