<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Need Help in calendar Weve got your back</name>
   <tag></tag>
   <elementGuidId>ec3f4977-25e3-474f-9814-afaf5ae53392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>63b4548d-cd9a-4c44-b1ba-9037f42fe246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Need Help in calendar? We've got your back</value>
      <webElementGuid>c4003284-2283-4c52-965d-9a028e9c5643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;mt-2&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-md-7&quot;]/h3[1]</value>
      <webElementGuid>f89e22a1-e2fb-4be4-80fa-dfd5911338d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/h3</value>
      <webElementGuid>1c47007b-267f-42ba-bbe5-9035e0b806a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='•'])[1]/preceding::h3[1]</value>
      <webElementGuid>41039b42-5cab-4f4c-9de2-878ee17bef5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How do I show my availability to provide companionship to seniors ?'])[1]/preceding::h3[1]</value>
      <webElementGuid>5b216c09-0b6a-40f2-a00b-0196040a22c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>2766390b-7e5e-4b66-b7cf-6b01382a6ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = concat(&quot;Need Help in calendar? We&quot; , &quot;'&quot; , &quot;ve got your back&quot;) or . = concat(&quot;Need Help in calendar? We&quot; , &quot;'&quot; , &quot;ve got your back&quot;))]</value>
      <webElementGuid>08de2d54-18f8-44de-a6de-f18b53713f4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
