<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Thank you</name>
   <tag></tag>
   <elementGuidId>876f41f9-9533-4e6f-b2e1-1483b5937079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.heading.h1.text-center.heading-thankyou</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>d165642d-23a9-4506-b6cc-03084b1c4a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading h1 text-center heading-thankyou</value>
      <webElementGuid>7634ecb7-8354-4b33-88a6-c190d45c5ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you!</value>
      <webElementGuid>9451af4d-b452-4531-bee5-f6366a887f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container wrapper&quot;]/div[@class=&quot;mx-auto thankyou-container&quot;]/h1[@class=&quot;heading h1 text-center heading-thankyou&quot;]</value>
      <webElementGuid>eed6571b-888f-4867-b76c-d38a3fa2ec25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/h1</value>
      <webElementGuid>c9841149-2d2b-4840-b2ad-8c02636d071e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>59550f59-c6c9-4111-8761-33aa68fed1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Thank you!' or . = 'Thank you!')]</value>
      <webElementGuid>113c4d5c-2857-416f-ae4a-5707ab8fc19e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
