<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_Please_check_email</name>
   <tag></tag>
   <elementGuidId>febd087a-b9fe-43ce-92cd-ae10a572cc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.text-success.text-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>25a4cfe6-56a1-4604-a0c7-c279e93522b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success text-center</value>
      <webElementGuid>e1e02a46-8ac8-4660-8d32-39f6cc025591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please check the email address pgpalakgupta17@gmail.com for instructions to reset your password.</value>
      <webElementGuid>a653f577-37ee-4313-897a-d50a439a32fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container wrapper&quot;]/div[@class=&quot;main--container&quot;]/div[@class=&quot;row justify-content-between&quot;]/div[@class=&quot;col-12 col-md-6 login-container mx-auto mx-md-0&quot;]/div[@class=&quot;login-sign-up--innercontainer&quot;]/div[@class=&quot;login-forget-container&quot;]/div[1]/p[@class=&quot;text-success text-center&quot;]</value>
      <webElementGuid>5cdee2e7-1d1d-45f7-a50a-eda1445ba984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div/p[2]</value>
      <webElementGuid>d87db598-43f4-4352-88ca-e7192e79bcb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>3031c452-9cee-4176-a89a-6d3ecea2e034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Please check the email address pgpalakgupta17@gmail.com for instructions to reset your password.' or . = 'Please check the email address pgpalakgupta17@gmail.com for instructions to reset your password.')]</value>
      <webElementGuid>e5c073bf-9607-4bb5-af7b-b19df44cfc61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
