<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mobileNumber</name>
   <tag></tag>
   <elementGuidId>fc6217dd-567c-4462-8cc4-e63f2c08c039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputPhoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputPhoneNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2bcc496-820f-4b03-adbf-6a2ba5738f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>dd994d8b-6b6a-48a7-8d2d-6ff6cafd93d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>dbb007c1-7dac-4352-8714-13e43ddc23a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPhoneNumber</value>
      <webElementGuid>ed0322a9-d969-424e-82fc-265607a1041a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>+1 (234) 567-8910</value>
      <webElementGuid>83a4c96a-e7b3-45e1-b1a9-826fc2ae0407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobileNumber</value>
      <webElementGuid>cf6ce49a-2c09-4642-9074-926ec0901c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputPhoneNumber&quot;)</value>
      <webElementGuid>9175b8cf-5262-4375-8790-3a206730c9a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputPhoneNumber']</value>
      <webElementGuid>da6851a9-1be2-436a-a798-888ff0ad416b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>d0ebcfe7-1886-4a14-b9d7-a0b6bae633bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>902a2ad0-427a-45cb-92d7-977afab43897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'inputPhoneNumber' and @placeholder = '+1 (234) 567-8910' and @name = 'mobileNumber']</value>
      <webElementGuid>426f0ff7-1e2f-4e76-8b9e-70531407bde9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
