<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a city in MarylandBaltimoreFr_198150</name>
   <tag></tag>
   <elementGuidId>10d2a0a0-a742-463b-afe3-f03a27f194b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d4ee0d40-73bc-4795-b2d3-b3d9880ea474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>02a35dc7-a9c3-42c0-b48d-d4d22cf7fd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCity</value>
      <webElementGuid>7e0770ef-e84d-4f9f-9b26-fe6c2f44c1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>8dcdbe91-c923-47a1-a2ab-0b2c460a1b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a city in MarylandBaltimoreFrederickRockvilleGaithersburgBowieHagerstownAnnapolis</value>
      <webElementGuid>bcc434ab-35b8-4191-93c7-a8c5b4fdf19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCity&quot;)</value>
      <webElementGuid>d2bf6d1c-c7d0-4f26-aba3-366c046d62fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputCity']</value>
      <webElementGuid>bc3981e5-b461-409e-80d1-cc903ae79629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>c8c876d7-cd8e-4fb4-a915-02eee6899acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/select</value>
      <webElementGuid>fe267479-0dec-4d0f-8337-0e34168a6583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputCity' and @name = 'city' and (text() = 'Select a city in MarylandBaltimoreFrederickRockvilleGaithersburgBowieHagerstownAnnapolis' or . = 'Select a city in MarylandBaltimoreFrederickRockvilleGaithersburgBowieHagerstownAnnapolis')]</value>
      <webElementGuid>1864a25a-d4ae-47bb-861f-0ac0e5ef046f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
