<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_2. Family and Community Involvement</name>
   <tag></tag>
   <elementGuidId>622b5d84-a5ce-4876-9817-57914d227633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container-category']/form/div/div[2]/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f148faab-3971-4a57-8174-2885500fcdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading h3</value>
      <webElementGuid>a0429781-27f6-497d-a51b-2005a057155e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2. Family and Community Involvement*</value>
      <webElementGuid>e6e7dc5b-8b54-434e-a617-495fb657b9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container-category&quot;)/form[1]/div[@class=&quot;row justify-content-between p-0&quot;]/div[@class=&quot;p-0&quot;]/div[@class=&quot;col-12 p-0 my-3 border border-secondary-subtle shadow-sm rounded-bottom&quot;]/div[@class=&quot;row m-0 border border-bottom-secondary-subtle&quot;]/div[@class=&quot;col-11 p-2&quot;]/h1[@class=&quot;heading h3&quot;]</value>
      <webElementGuid>eca04baf-1969-4e16-bd9a-4af4eb9dafe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container-category']/form/div/div[2]/div/div/div/h1</value>
      <webElementGuid>8e29782d-8a97-444b-83d2-d001294524f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/h1</value>
      <webElementGuid>2475a795-7196-4ecd-ac69-9bc5326513e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '2. Family and Community Involvement*' or . = '2. Family and Community Involvement*')]</value>
      <webElementGuid>3f3d5956-c4cc-42ba-8f82-12a65dee2e17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
