<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__emergencyAddress</name>
   <tag></tag>
   <elementGuidId>21252f84-f21f-46e8-90f0-454a7f8f0a7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmergencyAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e2afad6-1857-49ac-9c14-4fb8f7917c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>f8115131-7165-4bcb-92b3-8bc4750ef042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2115d8f-fc89-4d38-8604-249f9ad035aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyAddress</value>
      <webElementGuid>43884da4-257e-4f87-a4a1-035ff7bb4648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: 4910 Pin Oak Drive NY</value>
      <webElementGuid>21c9841f-3ee1-4f8a-8fa8-e72b15dcabbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyAddress</value>
      <webElementGuid>bfbf3871-fb12-443c-83cf-707ee5699c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyAddress&quot;)</value>
      <webElementGuid>556d3168-22f5-470d-bb94-9a704fd88443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmergencyAddress']</value>
      <webElementGuid>5a62e2c3-7e1b-4bcc-b52d-6539db61819e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>a72bc633-92b0-421f-9a85-b349da039681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>d93facf7-66f5-413a-b566-e3410f6da965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputEmergencyAddress' and @placeholder = 'Example: 4910 Pin Oak Drive NY' and @name = 'emergencyAddress']</value>
      <webElementGuid>ac9eec1a-ab1f-4a98-bf94-0ae00f32e0b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
