<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Other No_hippa</name>
   <tag></tag>
   <elementGuidId>270d6adb-30df-4ccf-b5e7-ca6bac13ad1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputHippaPolicy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputHippaPolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>588cf958-2734-436f-8d37-68a77fc08052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>ae4d7a83-1f93-42f8-8acf-7ddcf2aa1d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputHippaPolicy</value>
      <webElementGuid>e62ab989-f565-47e9-bc9a-765f26daee9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5036f598-299c-48da-bd36-595da0127c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hippa</value>
      <webElementGuid>22c4352a-829f-4c5d-87fa-596e177eb09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputHippaPolicy&quot;)</value>
      <webElementGuid>2bd83c3c-dc9e-400f-ae38-6a7709512d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputHippaPolicy']</value>
      <webElementGuid>92098ce7-817f-444d-b996-47b00bf1b298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[3]/div/div/input</value>
      <webElementGuid>269c78f9-ef80-4462-a451-f9305c004b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>42672821-6940-4d21-b71a-812b9b3cee6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputHippaPolicy' and @type = 'checkbox' and @name = 'hippa']</value>
      <webElementGuid>64eb6e5d-ce07-455f-b5c0-ce2bf024d30e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
