<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Other No_emergencyOtherNumber</name>
   <tag></tag>
   <elementGuidId>79cde581-ce6a-4e6b-b3eb-a90d278ec593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyOtherNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmergencyOtherNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c297276-6c0b-4388-968a-12f9a28d69b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>6b08ce46-a15b-46a5-839b-0fbe8255ad30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>995e6c7d-bf30-4eab-aff6-b2dbe9a8cadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyOtherNumber</value>
      <webElementGuid>e5a83b5c-0235-4b15-8ba2-0e10a83e2d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>+1 (234) 567-8910</value>
      <webElementGuid>be32202e-baab-48ac-b2f7-ec8f54412375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyOtherNumber</value>
      <webElementGuid>7d6b8d9d-8280-481a-b384-32335e7b4a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyOtherNumber&quot;)</value>
      <webElementGuid>74cf4ada-c428-44e0-9e3b-3a05cc598c5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmergencyOtherNumber']</value>
      <webElementGuid>f43bc3ad-7a77-47e9-b727-dcd2bfcb67cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[6]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>c48f789f-31c7-49e9-9850-73fb42754141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>4e87425c-ec6b-46ab-abb2-24b5db50bb9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'inputEmergencyOtherNumber' and @placeholder = '+1 (234) 567-8910' and @name = 'emergencyOtherNumber']</value>
      <webElementGuid>f8fc1ffc-34df-420f-b72d-1ab1cc23d445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
