<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectEC_City</name>
   <tag></tag>
   <elementGuidId>825a55a1-e33a-4d07-9315-e854a395a600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputEmergencyCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ffa6dc52-7d49-48a0-babb-8ba59e7638da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>c5cfc2de-886f-432c-ac2f-70c526e4aafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyCity</value>
      <webElementGuid>2c2825a5-3235-4e7c-9025-71e6c0642517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyCity</value>
      <webElementGuid>2b30c007-88dc-4947-b7ed-878d22c7fcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a city in CaliforniaLos AngelesSan DiegoSan JoseSan FranciscoFresnoSacramentoLong BeachOaklandBakersfieldAnaheimSanta AnaRiversideStocktonChula VistaIrvineFremontSan BernardinoModestoFontanaOxnardMoreno ValleyHuntington BeachGlendaleSanta ClaritaGarden GroveOceansideRancho CucamongaSanta RosaOntarioLancasterElk GroveCoronaPalmdaleSalinasPomonaHaywardEscondidoTorranceSunnyvaleOrangeFullertonPasadenaThousand OaksVisaliaSimi ValleyConcordRosevilleVictorvilleSanta ClaraVallejoBerkeleyEl MonteDowneyCosta MesaInglewoodCarlsbadSan Buenaventura (Ventura)FairfieldWest CovinaMurrietaRichmondNorwalkAntiochTemeculaBurbankDaly CityRialtoSanta MariaEl CajonSan MateoClovisComptonJurupa ValleyVistaSouth GateMission ViejoVacavilleCarsonHesperiaSanta MonicaWestminsterReddingSanta BarbaraChicoNewport BeachSan LeandroSan MarcosWhittierHawthorneCitrus HeightsTracyAlhambraLivermoreBuena ParkMenifeeHemetLakewoodMercedChinoIndioRedwood CityLake ForestNapaTustinBellflowerMountain ViewChino HillsBaldwin ParkAlamedaUplandSan RamonFolsomPleasantonUnion CityPerrisMantecaLynwoodApple ValleyRedlandsTurlockMilpitasRedondo BeachRancho CordovaYorba LindaPalo AltoDavisCamarilloWalnut CreekPittsburgSouth San FranciscoYuba CitySan ClementeLaguna NiguelPico RiveraMontebelloLodiMaderaSanta CruzLa HabraEncinitasMonterey ParkTulareCupertinoGardenaNational CityRocklinPetalumaHuntington ParkSan RafaelLa MesaArcadiaFountain ValleyDiamond BarWoodlandSanteeLake ElsinorePortervilleParamountEastvaleRosemeadHanfordHighlandBrentwoodNovatoColtonCathedral CityDelanoYucaipaWatsonvillePlacentiaGlendoraGilroyPalm DesertCerritosWest SacramentoAliso ViejoPowayLa MiradaRancho Santa MargaritaCypressDublinCovinaAzusaPalm SpringsSan Luis ObispoCeresSan JacintoLincolnNewarkLompocEl CentroDanvilleBell GardensCoachellaRancho Palos VerdesSan BrunoRohnert ParkBreaLa PuenteCampbellSan GabrielBeaumontMorgan HillCulver CityCalexicoStantonLa QuintaPacificaMontclairOakleyMonroviaLos BanosMartinez</value>
      <webElementGuid>a5ce4746-977f-44be-86b3-547eb8382075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyCity&quot;)</value>
      <webElementGuid>ed655038-cc77-4aee-8bc3-3b6a854b0dea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputEmergencyCity']</value>
      <webElementGuid>49eb17c9-98ee-47ea-98f8-027d0fb8b45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>c6c56a63-d984-4564-ae3b-0a029e7df7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>e5bb7cc8-ae68-4753-9c17-621fba37987c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputEmergencyCity' and @name = 'emergencyCity' and (text() = 'Select a city in CaliforniaLos AngelesSan DiegoSan JoseSan FranciscoFresnoSacramentoLong BeachOaklandBakersfieldAnaheimSanta AnaRiversideStocktonChula VistaIrvineFremontSan BernardinoModestoFontanaOxnardMoreno ValleyHuntington BeachGlendaleSanta ClaritaGarden GroveOceansideRancho CucamongaSanta RosaOntarioLancasterElk GroveCoronaPalmdaleSalinasPomonaHaywardEscondidoTorranceSunnyvaleOrangeFullertonPasadenaThousand OaksVisaliaSimi ValleyConcordRosevilleVictorvilleSanta ClaraVallejoBerkeleyEl MonteDowneyCosta MesaInglewoodCarlsbadSan Buenaventura (Ventura)FairfieldWest CovinaMurrietaRichmondNorwalkAntiochTemeculaBurbankDaly CityRialtoSanta MariaEl CajonSan MateoClovisComptonJurupa ValleyVistaSouth GateMission ViejoVacavilleCarsonHesperiaSanta MonicaWestminsterReddingSanta BarbaraChicoNewport BeachSan LeandroSan MarcosWhittierHawthorneCitrus HeightsTracyAlhambraLivermoreBuena ParkMenifeeHemetLakewoodMercedChinoIndioRedwood CityLake ForestNapaTustinBellflowerMountain ViewChino HillsBaldwin ParkAlamedaUplandSan RamonFolsomPleasantonUnion CityPerrisMantecaLynwoodApple ValleyRedlandsTurlockMilpitasRedondo BeachRancho CordovaYorba LindaPalo AltoDavisCamarilloWalnut CreekPittsburgSouth San FranciscoYuba CitySan ClementeLaguna NiguelPico RiveraMontebelloLodiMaderaSanta CruzLa HabraEncinitasMonterey ParkTulareCupertinoGardenaNational CityRocklinPetalumaHuntington ParkSan RafaelLa MesaArcadiaFountain ValleyDiamond BarWoodlandSanteeLake ElsinorePortervilleParamountEastvaleRosemeadHanfordHighlandBrentwoodNovatoColtonCathedral CityDelanoYucaipaWatsonvillePlacentiaGlendoraGilroyPalm DesertCerritosWest SacramentoAliso ViejoPowayLa MiradaRancho Santa MargaritaCypressDublinCovinaAzusaPalm SpringsSan Luis ObispoCeresSan JacintoLincolnNewarkLompocEl CentroDanvilleBell GardensCoachellaRancho Palos VerdesSan BrunoRohnert ParkBreaLa PuenteCampbellSan GabrielBeaumontMorgan HillCulver CityCalexicoStantonLa QuintaPacificaMontclairOakleyMonroviaLos BanosMartinez' or . = 'Select a city in CaliforniaLos AngelesSan DiegoSan JoseSan FranciscoFresnoSacramentoLong BeachOaklandBakersfieldAnaheimSanta AnaRiversideStocktonChula VistaIrvineFremontSan BernardinoModestoFontanaOxnardMoreno ValleyHuntington BeachGlendaleSanta ClaritaGarden GroveOceansideRancho CucamongaSanta RosaOntarioLancasterElk GroveCoronaPalmdaleSalinasPomonaHaywardEscondidoTorranceSunnyvaleOrangeFullertonPasadenaThousand OaksVisaliaSimi ValleyConcordRosevilleVictorvilleSanta ClaraVallejoBerkeleyEl MonteDowneyCosta MesaInglewoodCarlsbadSan Buenaventura (Ventura)FairfieldWest CovinaMurrietaRichmondNorwalkAntiochTemeculaBurbankDaly CityRialtoSanta MariaEl CajonSan MateoClovisComptonJurupa ValleyVistaSouth GateMission ViejoVacavilleCarsonHesperiaSanta MonicaWestminsterReddingSanta BarbaraChicoNewport BeachSan LeandroSan MarcosWhittierHawthorneCitrus HeightsTracyAlhambraLivermoreBuena ParkMenifeeHemetLakewoodMercedChinoIndioRedwood CityLake ForestNapaTustinBellflowerMountain ViewChino HillsBaldwin ParkAlamedaUplandSan RamonFolsomPleasantonUnion CityPerrisMantecaLynwoodApple ValleyRedlandsTurlockMilpitasRedondo BeachRancho CordovaYorba LindaPalo AltoDavisCamarilloWalnut CreekPittsburgSouth San FranciscoYuba CitySan ClementeLaguna NiguelPico RiveraMontebelloLodiMaderaSanta CruzLa HabraEncinitasMonterey ParkTulareCupertinoGardenaNational CityRocklinPetalumaHuntington ParkSan RafaelLa MesaArcadiaFountain ValleyDiamond BarWoodlandSanteeLake ElsinorePortervilleParamountEastvaleRosemeadHanfordHighlandBrentwoodNovatoColtonCathedral CityDelanoYucaipaWatsonvillePlacentiaGlendoraGilroyPalm DesertCerritosWest SacramentoAliso ViejoPowayLa MiradaRancho Santa MargaritaCypressDublinCovinaAzusaPalm SpringsSan Luis ObispoCeresSan JacintoLincolnNewarkLompocEl CentroDanvilleBell GardensCoachellaRancho Palos VerdesSan BrunoRohnert ParkBreaLa PuenteCampbellSan GabrielBeaumontMorgan HillCulver CityCalexicoStantonLa QuintaPacificaMontclairOakleyMonroviaLos BanosMartinez')]</value>
      <webElementGuid>264b6762-5e2c-4ed4-99c9-2e9c453ca6a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
