<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a city in MichiganDetroitGran_ff8a02</name>
   <tag></tag>
   <elementGuidId>e3ef9276-72af-4e53-af4f-3a3457940e7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputEmergencyCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b23f083d-9c71-4be3-99a4-96393a9f9ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>48e55e56-31dd-407d-8ba8-49b2414e8444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyCity</value>
      <webElementGuid>bdaa6dc6-e16a-41fd-9442-4caa992e4a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyCity</value>
      <webElementGuid>6f66dfa2-961e-4c52-9c34-b3240dcb7d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a city in MichiganDetroitGrand RapidsWarrenSterling HeightsAnn ArborLansingFlintDearbornLivoniaWestlandTroyFarmington HillsKalamazooWyomingSouthfieldRochester HillsTaylorPontiacSt. Clair ShoresRoyal OakNoviDearborn HeightsBattle CreekSaginawKentwoodEast LansingRosevillePortageMidlandLincoln ParkMuskegon</value>
      <webElementGuid>95b8d66b-4776-4f3e-932c-aed55b02df86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyCity&quot;)</value>
      <webElementGuid>a596eeed-80db-4921-91f2-78a9037a4ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputEmergencyCity']</value>
      <webElementGuid>f4873408-a3c4-48cd-bd85-98cfc6ff0cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[3]/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>41682d15-e824-4eb1-a1da-4ac525ab70d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>d61cef51-cb74-4772-963a-5622adb3c144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputEmergencyCity' and @name = 'emergencyCity' and (text() = 'Select a city in MichiganDetroitGrand RapidsWarrenSterling HeightsAnn ArborLansingFlintDearbornLivoniaWestlandTroyFarmington HillsKalamazooWyomingSouthfieldRochester HillsTaylorPontiacSt. Clair ShoresRoyal OakNoviDearborn HeightsBattle CreekSaginawKentwoodEast LansingRosevillePortageMidlandLincoln ParkMuskegon' or . = 'Select a city in MichiganDetroitGrand RapidsWarrenSterling HeightsAnn ArborLansingFlintDearbornLivoniaWestlandTroyFarmington HillsKalamazooWyomingSouthfieldRochester HillsTaylorPontiacSt. Clair ShoresRoyal OakNoviDearborn HeightsBattle CreekSaginawKentwoodEast LansingRosevillePortageMidlandLincoln ParkMuskegon')]</value>
      <webElementGuid>f9d9e869-0017-40ee-af8c-49626e2a9d74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
