<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_EC_Relation</name>
   <tag></tag>
   <elementGuidId>b981d86b-bc2a-48a0-9a07-1dbdf3634e03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyPersonRelation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputEmergencyPersonRelation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4ef2b415-e71e-4279-a76a-00145fcf4f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>f10cf45f-ca3d-4769-90d5-6ddac0ebfb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyPersonRelation</value>
      <webElementGuid>6b47abee-471d-4a32-9b1f-1d22f583e507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyPersonRelation</value>
      <webElementGuid>fe6fe08f-dc26-4d96-a16a-7cb6f7f4b294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select Relation SpouseSonDaughterFamilyOtherPartnerAcquaintance</value>
      <webElementGuid>dce7c6e4-8998-4283-92f0-cf045cc7c4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyPersonRelation&quot;)</value>
      <webElementGuid>bdecef89-f1ae-45e2-ad55-127cb913329b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputEmergencyPersonRelation']</value>
      <webElementGuid>5da3a6ba-f709-446c-a33e-4db0bac495c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>8421fc5e-93d5-422b-92b8-e694dbce1e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>47d42ebc-d4b5-4c1d-beed-91ffb04cb420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputEmergencyPersonRelation' and @name = 'emergencyPersonRelation' and (text() = 'Please Select Relation SpouseSonDaughterFamilyOtherPartnerAcquaintance' or . = 'Please Select Relation SpouseSonDaughterFamilyOtherPartnerAcquaintance')]</value>
      <webElementGuid>81d1ce03-0bed-4ccc-afb4-4e80fcbc54a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
