<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a state first</name>
   <tag></tag>
   <elementGuidId>2c24ef7d-7ae8-46f2-b783-eb2a15f33281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyCity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputEmergencyCity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>83ac8928-f27f-4517-8d24-837f077cecba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>519fa614-efda-4f82-8d14-0f4f2dacfbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyCity</value>
      <webElementGuid>30f6a27e-5889-42f8-8c8d-f7eb415023aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyCity</value>
      <webElementGuid>58b9b96a-d89e-4b3b-85ed-e1fc3447b9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a state first</value>
      <webElementGuid>601f99fa-f971-4712-aacb-dae964f04eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyCity&quot;)</value>
      <webElementGuid>b868818d-9360-4eba-9e63-b4d16b9c1491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputEmergencyCity']</value>
      <webElementGuid>e35cff0c-2def-43b7-ae3d-6bc4f85a8263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>19b0a507-6d8b-4b9b-902b-7fc199274fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>9d6ee145-aa7d-4063-aafe-ebe09440b59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputEmergencyCity' and @name = 'emergencyCity' and (text() = 'Select a state first' or . = 'Select a state first')]</value>
      <webElementGuid>fbc83481-60df-43d3-af79-3f09a3f8b8ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
