<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_HIPPA_Consent</name>
   <tag></tag>
   <elementGuidId>cdc7a3ff-da99-4959-adc8-900810638278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputHippaPolicy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputHippaPolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c6a63fa-40f3-4e3d-9dfb-211c514d8f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>4e9e148f-5148-472d-b9ee-8f8e2616e21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputHippaPolicy</value>
      <webElementGuid>57a80265-6271-4d7d-bf10-632d2675051e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a34ff487-fef0-428d-b24e-41684b56219f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hippa</value>
      <webElementGuid>2b5700d7-3c7e-455c-90c1-0648f2a0d3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputHippaPolicy&quot;)</value>
      <webElementGuid>84276d6f-2413-49ef-8705-89df0106d77c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputHippaPolicy']</value>
      <webElementGuid>9fd5d68a-a1ef-4e1f-8c16-af727829afea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[4]/div/div/input</value>
      <webElementGuid>b2bfab06-2007-4f9a-a4bd-a893b71111d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>7abc77db-dda3-44d7-b1da-2f9fce173f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputHippaPolicy' and @type = 'checkbox' and @name = 'hippa']</value>
      <webElementGuid>ddc2f50a-5c5a-4067-9062-52c80ad76d49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
