<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input__EC_MobileNumber1</name>
   <tag></tag>
   <elementGuidId>acae17b9-d8e1-4aaf-affb-cc55f8876839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyMobileNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmergencyMobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5967852c-5759-454a-b17d-93cb8681e718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>63c31916-a41c-4a76-a2ff-9704495fb6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>6b5cd1ef-8d6b-4c14-85cd-761009410460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyMobileNumber</value>
      <webElementGuid>7c054d6d-9fd5-4ff2-b8a0-dc8747d156e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>+1 (234) 567-8910</value>
      <webElementGuid>4a1a0121-bf18-4822-9328-b9a7814d749e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyMobileNumber</value>
      <webElementGuid>4e138f64-8311-48e6-93e2-d7b68dbf9350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyMobileNumber&quot;)</value>
      <webElementGuid>2982a209-bf52-4b16-886f-6e21c999cb81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmergencyMobileNumber']</value>
      <webElementGuid>00b94933-ae09-4c51-8ac8-089ac95a8adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[3]/div/div[2]/div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>19f2dd96-7060-421b-a27d-ffce96820adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>62552a0e-f363-48c0-b7f1-968c11489248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'inputEmergencyMobileNumber' and @placeholder = '+1 (234) 567-8910' and @name = 'emergencyMobileNumber']</value>
      <webElementGuid>e0968ae8-b7a5-4f2d-8c5f-ac9b5848490f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
