<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_EC_Address2</name>
   <tag></tag>
   <elementGuidId>161f0c41-84ce-48e9-b6f1-1953c65a6665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyAddress2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmergencyAddress2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c34526e9-1bbe-47f3-974a-e47783c30476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>618a6f56-d4f9-4b6b-9a2d-b6afb87152e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49f64bcf-9ef0-4013-8957-ac20f3b88c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyAddress2</value>
      <webElementGuid>9be600f1-aae3-4402-9caf-bad7855778fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: 4910 Pin Oak Drive NY</value>
      <webElementGuid>5530d099-8688-426c-9df1-d37ed1cc17ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyAddress2</value>
      <webElementGuid>2cab0e7e-ee0a-4c48-b795-0541d462bd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyAddress2&quot;)</value>
      <webElementGuid>b0248879-d761-406d-831c-eaf310eda6a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmergencyAddress2']</value>
      <webElementGuid>e225d2c0-5196-414b-a72a-c10ca82ca518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[3]/div/div[2]/div[4]/div/div[2]/input</value>
      <webElementGuid>785b3b8e-f339-4747-91b9-3244d2b056f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[4]/div/div[2]/input</value>
      <webElementGuid>41ee4041-e0dc-45c0-b658-28207fc80c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputEmergencyAddress2' and @placeholder = 'Example: 4910 Pin Oak Drive NY' and @name = 'emergencyAddress2']</value>
      <webElementGuid>b3ebcf54-0bb4-4868-97f7-d9ed7ed1de15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
