<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input__EC_Address1</name>
   <tag></tag>
   <elementGuidId>fb19f958-5534-4918-8da0-010b1980dbbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmergencyAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdbc9488-d31e-4edb-b443-5d7f701a87c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>3c75fc1d-27ec-438e-973f-34cfeeec1f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>900d1aea-d6e1-4016-a414-4327b4e7b02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyAddress</value>
      <webElementGuid>4d6b45f7-fbcd-4511-a6e9-fb1728b39e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: 4910 Pin Oak Drive NY</value>
      <webElementGuid>3406b31c-8b6d-4e47-859f-dfc98be86812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyAddress</value>
      <webElementGuid>88389718-3fc7-4031-bde2-93c3bdf98a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyAddress&quot;)</value>
      <webElementGuid>b97042b8-417f-496c-844c-42bcb4760681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmergencyAddress']</value>
      <webElementGuid>71111b97-639d-4721-a4f3-1344ab57344d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[3]/div/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>03d7f172-4698-47bf-87d9-cd597b100460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>f97f2531-ac8e-476a-9d0f-ca5af96825a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputEmergencyAddress' and @placeholder = 'Example: 4910 Pin Oak Drive NY' and @name = 'emergencyAddress']</value>
      <webElementGuid>1f8d67df-f3f5-414c-ab3d-a2ef013d29a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
