<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_EC_Relation</name>
   <tag></tag>
   <elementGuidId>630cb00c-171b-4f4c-877e-bc56957d9b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyPersonRelation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputEmergencyPersonRelation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>130bd3f5-ea5c-4bc4-ac91-6f2bb92f36ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>07b5e1aa-58c7-4c9a-8ea8-3393292df3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyPersonRelation</value>
      <webElementGuid>e608e52d-c2c0-4a85-9bf0-2a47c6afe034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyPersonRelation</value>
      <webElementGuid>51c77c37-c667-4455-a90c-5608b24d7b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select Relation SpouseSonDaughterFamilyOtherPartnerAcquaintance</value>
      <webElementGuid>3f74d1d0-3b0f-4b74-b73d-a0d322737795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyPersonRelation&quot;)</value>
      <webElementGuid>07563744-a67e-458a-af38-4ae6f88c6193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputEmergencyPersonRelation']</value>
      <webElementGuid>d34336c1-cc4c-479d-bd0d-e862178c7d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[3]/div/div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>4fb206c2-219b-454b-9c95-721fdae797f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/following::select[1]</value>
      <webElementGuid>ffd45093-8a61-4dc8-98ff-d4894f46a3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/preceding::select[1]</value>
      <webElementGuid>c48bddfd-81f5-4a37-a2ea-ed46e834040a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>71be6abf-b26f-408d-bec9-0a5032643fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputEmergencyPersonRelation' and @name = 'emergencyPersonRelation' and (text() = 'Please Select Relation SpouseSonDaughterFamilyOtherPartnerAcquaintance' or . = 'Please Select Relation SpouseSonDaughterFamilyOtherPartnerAcquaintance')]</value>
      <webElementGuid>d9e9e2e3-990a-4abf-a8cc-537bb70fb18c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
