<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_We are in the process of creating</name>
   <tag></tag>
   <elementGuidId>f2ed6323-e51f-46fc-9404-6d52776142a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.spinner-text--category</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ffc86691-46e4-4c4f-a26e-3781b35c1388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spinner-text--category</value>
      <webElementGuid>81820ac0-0252-4746-8838-bccd6a968d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We are in the process of creating and categorizing your profile based on the information you provided.</value>
      <webElementGuid>8d69e9e4-d566-45c3-8e93-1eaed845715d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;Spinner&quot;]/div[@class=&quot;spinner-children&quot;]/div[@class=&quot;spinner-text--container&quot;]/p[@class=&quot;spinner-text--category&quot;]</value>
      <webElementGuid>56263378-9ac6-43bb-b771-4e8a3953a789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/p</value>
      <webElementGuid>59d20c82-5606-46fb-9577-b6ab9a09b25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/p</value>
      <webElementGuid>9f8ff175-cd6d-4a2d-bb3f-6c36a6d81d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'We are in the process of creating and categorizing your profile based on the information you provided.' or . = 'We are in the process of creating and categorizing your profile based on the information you provided.')]</value>
      <webElementGuid>1246792b-b6a7-4b2d-8648-67be46a70729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
