<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Need Help in calendar Weve got your back (1)</name>
   <tag></tag>
   <elementGuidId>5d7e70ef-2974-4103-a929-bc9a1753f84f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>a0cbac83-787c-45bb-b9a2-9d694f9f25d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Need Help in calendar? We've got your back</value>
      <webElementGuid>91bd12c8-195b-497b-941a-8153042b082b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;mt-2&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-md-7&quot;]/h3[1]</value>
      <webElementGuid>6d8e22da-1d5f-4c83-a122-e4ddbdb36f7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/h3</value>
      <webElementGuid>b16547f5-5962-4d54-8776-895e51a1eab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='•'])[1]/preceding::h3[1]</value>
      <webElementGuid>bb0b827c-30ec-420a-9439-ae49af48b5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How do I show my availability to provide companionship to seniors ?'])[1]/preceding::h3[1]</value>
      <webElementGuid>a9eaa23c-4e44-4f93-b990-4ecae78f8d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>3bd2fe9b-472b-4e3a-84a4-173058b764db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = concat(&quot;Need Help in calendar? We&quot; , &quot;'&quot; , &quot;ve got your back&quot;) or . = concat(&quot;Need Help in calendar? We&quot; , &quot;'&quot; , &quot;ve got your back&quot;))]</value>
      <webElementGuid>1b19ddce-c03a-4572-bf4b-5a7be85d4caf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
