<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_raj (Companion)</name>
   <tag></tag>
   <elementGuidId>5ac2dd34-21b6-420a-96ff-69197c2c1413</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.header-name-text.m-1.text-capitalize</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2997d55a-b5b2-46dd-9633-7faff5832e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-name-text m-1 text-capitalize</value>
      <webElementGuid>c900a251-ef78-42af-be34-9215b7f1d22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>raj (Companion)</value>
      <webElementGuid>a706d8e9-f988-43f3-a875-a5b8bbe71c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/nav[@class=&quot;container-fluid mx-auto navbar navbar-expand-lg navbar-light bg-light header-container--size p-0 text-left&quot;]/div[@class=&quot;row w-100 justify-content-between mx-4 my-1&quot;]/div[@class=&quot;col-6 col-sm-3 col-md-3 header-name justify-content-end&quot;]/div[@class=&quot;header-name-container&quot;]/p[@class=&quot;header-name-text m-1 text-capitalize&quot;]</value>
      <webElementGuid>a4461538-51f8-420b-9db2-ef7048883777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div/div[2]/div/p</value>
      <webElementGuid>6b5470bc-b435-4156-bb7f-afd22d05f939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>55508be1-1086-4e0d-8022-0297bcb97a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'raj (Companion)' or . = 'raj (Companion)')]</value>
      <webElementGuid>c3510bf9-63fa-417a-a6c0-99f0550e39fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
