<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Available_To</name>
   <tag></tag>
   <elementGuidId>d7957c18-6cba-4ed2-ada0-10dc2df639bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='availableTo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;availableTo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6928b55c-0f06-4d96-b2fd-4328c630fed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control select-item-icon</value>
      <webElementGuid>256e65b6-90fc-48f3-90cd-d2a2f7a42ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>availableTo</value>
      <webElementGuid>7a610ec8-f2a4-4877-a64d-4373be6a03e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select10:00 AM10:30 AM11:00 AM11:30 AM12:00 PM12:30 PM01:00 PM01:30 PM02:00 PM02:30 PM03:00 PM03:30 PM04:00 PM04:30 PM05:00 PM05:30 PM06:00 PM06:30 PM07:00 PM</value>
      <webElementGuid>fb6fccb9-485e-400f-9df6-1309640efc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;mx-auto Calender-container&quot;]/div[@class=&quot;card flex justify-content-center&quot;]/div[@class=&quot;Modal&quot;]/div[@class=&quot;modal-addEvent-Container&quot;]/form[@class=&quot;form-group mx-auto&quot;]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;col-6 dropDown-container&quot;]/select[@class=&quot;form-control select-item-icon&quot;]</value>
      <webElementGuid>2fd0208d-cef3-4bea-91b6-cc61a45250fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='availableTo']</value>
      <webElementGuid>7b60286d-abb2-433b-9543-3dd3bcd17aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div[2]/div/form/div/div[2]/select</value>
      <webElementGuid>2adf0537-b24a-43c7-9aea-6ada9cc77bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>08e01f6d-ac5e-46a5-9e38-54c3256363da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'availableTo' and (text() = 'Please Select10:00 AM10:30 AM11:00 AM11:30 AM12:00 PM12:30 PM01:00 PM01:30 PM02:00 PM02:30 PM03:00 PM03:30 PM04:00 PM04:30 PM05:00 PM05:30 PM06:00 PM06:30 PM07:00 PM' or . = 'Please Select10:00 AM10:30 AM11:00 AM11:30 AM12:00 PM12:30 PM01:00 PM01:30 PM02:00 PM02:30 PM03:00 PM03:30 PM04:00 PM04:30 PM05:00 PM05:30 PM06:00 PM06:30 PM07:00 PM')]</value>
      <webElementGuid>b5c05042-8d85-449d-8315-864c893969a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
