<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Name</name>
   <tag></tag>
   <elementGuidId>efbbef6d-f3b3-4f50-8eaa-705767e45500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/form/div[3]/div/div[2]/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.demographic-information-container-3 > div.row > div.col-sm-8.col-12 > div.col-12 > div.row.pt-3 > div.col-sm-12.col-12 > label.demographic-form-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>04aa8558-2ae9-4c09-bc39-9c5a3eaf12de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>inputEmergencyName</value>
      <webElementGuid>551d487b-e76c-4f57-af6d-04669c1f6db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demographic-form-label</value>
      <webElementGuid>135ba2df-e407-4272-b29e-a72f58c775b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name*</value>
      <webElementGuid>f5c77f4e-8dd2-46f3-9b83-7b1731559def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;demographic-container&quot;]/form[@class=&quot;row g-3&quot;]/div[@class=&quot;demographic-information-container-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8 col-12&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row pt-3&quot;]/div[@class=&quot;col-sm-12 col-12&quot;]/label[@class=&quot;demographic-form-label&quot;]</value>
      <webElementGuid>6b08b4d5-c7b4-4fd5-b28a-c48644bcd1d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[3]/div/div[2]/div/div/div/label</value>
      <webElementGuid>9d3630b4-eb6a-4884-8b24-3acc37388091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/label</value>
      <webElementGuid>236022ce-98fe-4299-8193-1a456481c197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Name*' or . = 'Name*')]</value>
      <webElementGuid>10bddf62-a14e-4355-bda9-4f3b1eb362a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
