<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Edit_expectation</name>
   <tag></tag>
   <elementGuidId>303ecefc-bfee-43d4-9a3a-7357e2a98ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='inputDescriptionExpectation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputDescriptionExpectation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c05700b5-7db8-4bfa-98b6-35f9cceb5d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>11b28e99-8eba-47e4-9177-1709d3929249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc98b72e-5bab-4e7b-894d-910ddc53efea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b6e558c1-dc83-4b8b-acb0-2fc0f1f5e5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputDescriptionExpectation</value>
      <webElementGuid>e8242d6c-7e48-4d46-88ca-cccda86665ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>You can add or delete your information</value>
      <webElementGuid>d1112b8a-1dbc-45a8-bb5f-2c1b9073c937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expectation</value>
      <webElementGuid>d706ac1a-8d73-4419-a3ae-a0815dc09344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputDescriptionExpectation&quot;)</value>
      <webElementGuid>bad68971-04d4-49ed-a320-af07c6630756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='inputDescriptionExpectation']</value>
      <webElementGuid>4d61630d-4f71-4e95-b6c2-8f06e7295546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div[3]/div/div[2]/textarea</value>
      <webElementGuid>23d77124-2bb5-4ff4-bbdb-207fd5264f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/textarea</value>
      <webElementGuid>f3411490-381e-4adc-9b85-39a922e72664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'inputDescriptionExpectation' and @placeholder = 'You can add or delete your information' and @name = 'expectation']</value>
      <webElementGuid>f158e2f2-e952-4f4a-83db-2333ef11b1d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
