<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Edit_Family_And_Community_Involvement</name>
   <tag></tag>
   <elementGuidId>e439c6a4-9be1-4d10-bab4-482e5286d0cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputDescriptionFamily</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='inputDescriptionFamily']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>80aa979a-a6b9-42bd-b9f9-417c2b2cae50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d38a1f40-3e69-4bbd-8d99-95f19a5de78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d2a8a39-e7b5-49ab-94b8-a21e61eaf480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>58249245-33cc-462d-8789-6c3cdcfda454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputDescriptionFamily</value>
      <webElementGuid>99f9ee42-48b2-48be-b739-622ca9500211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>You can add or delete your information</value>
      <webElementGuid>c26028a8-48e9-44ad-b957-8c357204b9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>family</value>
      <webElementGuid>c6ade4b9-5f9b-4042-abc7-76e9737ed2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputDescriptionFamily&quot;)</value>
      <webElementGuid>faefc13d-5c67-439b-87e0-95c08e27a4b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='inputDescriptionFamily']</value>
      <webElementGuid>5cfe662a-092b-4c10-ae0a-3f20e04d30fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container-category']/form/div/div[2]/div/div[2]/textarea</value>
      <webElementGuid>239c14a4-4d16-4f03-bccf-018a69e51b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/textarea</value>
      <webElementGuid>5f3d8113-beb8-401f-9856-27c7e716885a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'inputDescriptionFamily' and @placeholder = 'You can add or delete your information' and @name = 'family']</value>
      <webElementGuid>5bb71e18-186a-444d-a917-3e0a16368bec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
