<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_h1_Educational_Background</name>
   <tag></tag>
   <elementGuidId>125ff8de-6ce2-49a7-81bd-f766179a1d53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/form/div/div/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.heading.h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>0ca89d0d-0ca0-4691-b9ae-520f21400976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading h3</value>
      <webElementGuid>c0a78cf7-f18b-46c9-b031-0accaa6ad354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. Educational and Professional Background</value>
      <webElementGuid>33c21a9b-3fe7-4717-9b10-2c85aa4a5458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;px-2&quot;]/form[1]/div[@class=&quot;row justify-content-between p-0&quot;]/div[@class=&quot;p-0&quot;]/div[@class=&quot;col-12 p-0 my-3 border border-secondary-subtle shadow-sm rounded-bottom&quot;]/div[@class=&quot;row m-0 border border-bottom-secondary-subtle&quot;]/div[@class=&quot;col-11 p-2&quot;]/h1[@class=&quot;heading h3&quot;]</value>
      <webElementGuid>bd84dfe8-fdda-496b-ba94-17cfdc57b120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div/div/div/h1</value>
      <webElementGuid>58215dad-e6d6-485b-a20c-bdc4b6269e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please feel free to edit as appropriate.'])[1]/following::h1[1]</value>
      <webElementGuid>49f12e64-138c-4001-b337-e6d6b322bcde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Palak'])[1]/following::h1[2]</value>
      <webElementGuid>6ff2abc1-eeca-4138-8e68-1076e1ef280d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Re-record'])[1]/preceding::h1[4]</value>
      <webElementGuid>7fbd3898-09e7-4937-8f2c-a7f4fd82c0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; Continue'])[1]/preceding::h1[4]</value>
      <webElementGuid>4fca1321-7930-4133-b791-a22047e6fb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1. Educational and Professional Background']/parent::*</value>
      <webElementGuid>29182db1-0591-47de-acbe-7cf1c7a71c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/h1</value>
      <webElementGuid>de226933-da36-45a9-ac4c-b55e2a5007fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '1. Educational and Professional Background' or . = '1. Educational and Professional Background')]</value>
      <webElementGuid>d29d5bde-ae6d-4cc7-8634-0d87b431053f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
