<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_h1_Family_And_Community_Involvement</name>
   <tag></tag>
   <elementGuidId>a25675bb-11b5-4a7d-b29a-430263739488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container-category']/form/div/div[2]/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a5ddf6e7-5266-4194-afed-f29fb781a9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading h3</value>
      <webElementGuid>369ac054-2a9f-423c-bf5a-a5facd83bb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2. Family and Community Involvement*</value>
      <webElementGuid>b9e75804-c83d-4b59-bad0-3c82848220cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container-category&quot;)/form[1]/div[@class=&quot;row justify-content-between p-0&quot;]/div[@class=&quot;p-0&quot;]/div[@class=&quot;col-12 p-0 my-3 border border-secondary-subtle shadow-sm rounded-bottom&quot;]/div[@class=&quot;row m-0 border border-bottom-secondary-subtle&quot;]/div[@class=&quot;col-11 p-2&quot;]/h1[@class=&quot;heading h3&quot;]</value>
      <webElementGuid>247949e2-a2e0-4050-934b-1bbe206aab95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container-category']/form/div/div[2]/div/div/div/h1</value>
      <webElementGuid>c0123e12-70bd-4ae4-9ff1-ccd56f54bd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/h1</value>
      <webElementGuid>caea1b70-6553-425f-90ad-82f1630a3837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '2. Family and Community Involvement*' or . = '2. Family and Community Involvement*')]</value>
      <webElementGuid>390c56d0-be5e-44d3-adca-f1ff9348b282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
