<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_City</name>
   <tag></tag>
   <elementGuidId>cca77110-9e06-41e9-a405-c6618d320047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>96079667-a7bf-47d1-afe4-b23a4b3428a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>676af72c-d1fd-4725-bce5-d4f52235ff49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCity</value>
      <webElementGuid>6768f770-6bf7-425c-a547-adbbee1244f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>43229094-43a3-4ed4-b323-f1ca4c0aba91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a city in PennsylvaniaPhiladelphiaPittsburghAllentownErieReadingScrantonBethlehemLancasterHarrisburgAltoonaYorkState CollegeWilkes-Barre</value>
      <webElementGuid>864a27a9-eb74-4b13-a606-744a629a9b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCity&quot;)</value>
      <webElementGuid>3189f275-938d-4613-b4b8-57c7af388470</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputCity']</value>
      <webElementGuid>35d71018-d2f2-4924-a025-772b22df4690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>b66d195c-2334-4095-b283-cf25c56fc9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/select</value>
      <webElementGuid>7de47953-af80-4f8a-b52f-541eec40fe28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputCity' and @name = 'city' and (text() = 'Select a city in PennsylvaniaPhiladelphiaPittsburghAllentownErieReadingScrantonBethlehemLancasterHarrisburgAltoonaYorkState CollegeWilkes-Barre' or . = 'Select a city in PennsylvaniaPhiladelphiaPittsburghAllentownErieReadingScrantonBethlehemLancasterHarrisburgAltoonaYorkState CollegeWilkes-Barre')]</value>
      <webElementGuid>28b641c4-1332-4cfd-9369-76217cd209b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
