<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a state first</name>
   <tag></tag>
   <elementGuidId>e5db748a-be50-41b7-a7fb-8c838d31e328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4bb7c20c-e049-462c-a693-8fc0fd8c02d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>b2ef7a24-8174-4401-b076-370bbd62be73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCity</value>
      <webElementGuid>b5070a14-ec21-4733-a711-50fb7fb99749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>f43fd5f6-d3a4-470c-8ff9-a73e3902dc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a state first</value>
      <webElementGuid>c8c5b6ca-e2f0-4fac-b98a-93507276834c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCity&quot;)</value>
      <webElementGuid>a3c461a7-23c4-4062-a1e1-17818af9807d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputCity']</value>
      <webElementGuid>5928f924-d2a2-4908-8d66-898c1d2b4c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>cfb9c0d7-02a8-464e-b1ef-ff77f8206332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/select</value>
      <webElementGuid>667b02ca-1f25-457a-a24b-77bf19ccf007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputCity' and @name = 'city' and (text() = 'Select a state first' or . = 'Select a state first')]</value>
      <webElementGuid>311e389d-5e6a-4ce7-ac44-7c820a41e4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
