<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_State</name>
   <tag></tag>
   <elementGuidId>8dcd9097-cfaf-478f-958c-52d009cbe6b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputState']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputState</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff8504ad-c982-4c6f-90a9-5636abafd29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>b835f875-ebb3-4f34-a4b4-b63fe099ae26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputState</value>
      <webElementGuid>d560f094-2252-4a51-bae3-769f606418c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>state</value>
      <webElementGuid>cb65bd1e-04ce-44bb-861a-6a218af4104f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Example: TexasNew YorkCaliforniaIllinoisTexasPennsylvaniaArizonaFloridaIndianaOhioNorth CarolinaMichiganTennesseeMassachusettsWashingtonColoradoDistrict of ColumbiaMarylandKentuckyOregonOklahomaWisconsinNevadaNew MexicoMissouriVirginiaGeorgiaNebraskaMinnesotaKansasLouisianaHawaiiAlaskaNew JerseyIdahoAlabamaIowaArkansasUtahRhode IslandMississippiSouth DakotaConnecticutSouth CarolinaNew HampshireNorth DakotaMontanaDelawareMaineWyomingWest VirginiaVermont</value>
      <webElementGuid>ca9756f1-0f5e-44ca-b708-c8f4a46fc343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;demographic-container&quot;]/form[@class=&quot;row g-3&quot;]/div[@class=&quot;demographic-information-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8 col-12&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-12&quot;]/div[@class=&quot;row pt-3&quot;]/div[@class=&quot;col-sm-12 col-12&quot;]/select[@id=&quot;inputState&quot;]</value>
      <webElementGuid>f610f1ac-efcc-458c-bd91-dbbb2eae614f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputState']</value>
      <webElementGuid>70df548d-76e3-4a0a-8a18-37a27d79ec59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div[2]/div[5]/div/div/div/div[2]/select</value>
      <webElementGuid>c5461e22-9c4c-4431-b76f-76ed401df383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>76198630-eccd-4494-97d1-3dfca7974d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputState' and @name = 'state' and (text() = 'Example: TexasNew YorkCaliforniaIllinoisTexasPennsylvaniaArizonaFloridaIndianaOhioNorth CarolinaMichiganTennesseeMassachusettsWashingtonColoradoDistrict of ColumbiaMarylandKentuckyOregonOklahomaWisconsinNevadaNew MexicoMissouriVirginiaGeorgiaNebraskaMinnesotaKansasLouisianaHawaiiAlaskaNew JerseyIdahoAlabamaIowaArkansasUtahRhode IslandMississippiSouth DakotaConnecticutSouth CarolinaNew HampshireNorth DakotaMontanaDelawareMaineWyomingWest VirginiaVermont' or . = 'Example: TexasNew YorkCaliforniaIllinoisTexasPennsylvaniaArizonaFloridaIndianaOhioNorth CarolinaMichiganTennesseeMassachusettsWashingtonColoradoDistrict of ColumbiaMarylandKentuckyOregonOklahomaWisconsinNevadaNew MexicoMissouriVirginiaGeorgiaNebraskaMinnesotaKansasLouisianaHawaiiAlaskaNew JerseyIdahoAlabamaIowaArkansasUtahRhode IslandMississippiSouth DakotaConnecticutSouth CarolinaNew HampshireNorth DakotaMontanaDelawareMaineWyomingWest VirginiaVermont')]</value>
      <webElementGuid>cea92c8c-4007-4921-94e7-a27f864606bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
