<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input__DLExpireDate (1)</name>
   <tag></tag>
   <elementGuidId>8090d8b5-b495-4adc-9a74-bd7f25a2f1d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputDrivingExpirationDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputDrivingExpirationDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>faf8799d-7acc-422b-b167-ec7f64d5622f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>67fe0cff-3bdd-4bda-9c75-8675f44d1e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input dateInput</value>
      <webElementGuid>d583a5fe-a7d0-4009-96ae-904c0290c3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputDrivingExpirationDate</value>
      <webElementGuid>01c8a3c6-4f05-4065-81a5-f798c9c069e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>a41f3d8d-ee60-4d45-abb4-41d0a36191b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dlExpireDate</value>
      <webElementGuid>5dc6fdb2-078f-4b97-9cf9-f548ac558bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputDrivingExpirationDate&quot;)</value>
      <webElementGuid>7e2d2bef-a87a-419a-875d-538add5611fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputDrivingExpirationDate']</value>
      <webElementGuid>8f6302cf-4e10-4dbc-abc1-90b7d96c48b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>c4e12b54-1414-477d-bd69-5d9353baef18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>45e12366-d9f4-49fa-b9d9-89eadbce1bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'inputDrivingExpirationDate' and @placeholder = 'DD/MM/YYYY' and @name = 'dlExpireDate']</value>
      <webElementGuid>5ce3fac0-672f-4083-a6c1-3433db556299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
