<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__driveRange</name>
   <tag></tag>
   <elementGuidId>b3f87605-b81b-4d26-a313-af801abd2d3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputRangeDrive']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputRangeDrive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>155eae2f-8403-4b74-a0a2-0c0b44fb4547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demographic-input-range</value>
      <webElementGuid>2587aead-0670-4b7a-b58f-73b6a0a48203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputRangeDrive</value>
      <webElementGuid>d53af610-a2dd-418e-9294-60cb498237fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c32a0395-cb47-40d7-af2e-ef4a4e8c8668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>81e6e426-2b5f-46ec-9fac-5c921adc3741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>94</value>
      <webElementGuid>1db89ba6-6c35-46d5-9d74-fec16735dab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>c5f6d1c9-0602-4984-94e0-bb70f9b07456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>driveRange</value>
      <webElementGuid>c139b712-a8f3-4df3-967e-a6776f997b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>98aab2c6-410e-4034-9237-c31094b284f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputRangeDrive&quot;)</value>
      <webElementGuid>074d54ba-6592-41c7-a563-de416b639165</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputRangeDrive']</value>
      <webElementGuid>b8849275-208a-435a-b3a3-79bc4a8d1c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[4]/div/div[2]/input</value>
      <webElementGuid>a51ee04a-bb3d-4869-b9d1-2d0fba227ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[4]/div/div[2]/input</value>
      <webElementGuid>2fac3f6b-5aa7-458b-a4ca-1f1cc10196bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputRangeDrive' and @title = '94' and @type = 'range' and @name = 'driveRange']</value>
      <webElementGuid>081c8628-7e52-4924-99e2-77d95586849e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
