<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input__DLNumber</name>
   <tag></tag>
   <elementGuidId>6af0812c-613c-472c-8462-76566f2b1bc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputDlNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputDlNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>910724d2-4223-4808-bf00-e60ad82040f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>7b6629eb-b513-4f3f-a46f-6c7d15514406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>635c9fce-c2b6-4ebf-9447-a8ebdb774302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputDlNumber</value>
      <webElementGuid>7ed69770-fa63-40c1-a6f4-d0077661a3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: 190000001</value>
      <webElementGuid>988ab8dc-c678-482b-b077-0e357c407d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dlNumber</value>
      <webElementGuid>c1b5a33d-16cf-4cfa-87cf-5f7e1c99ea51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputDlNumber&quot;)</value>
      <webElementGuid>7e151a1b-10b1-44a7-8308-bba942163113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputDlNumber']</value>
      <webElementGuid>eac4ead5-1e19-4189-9d58-9784c5196248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>12129d0a-ba5a-4961-bc42-77eb7730e49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>9db53429-e8b5-4be4-bc78-aa83ba165972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputDlNumber' and @placeholder = 'Example: 190000001' and @name = 'dlNumber']</value>
      <webElementGuid>8484b14b-9ffe-4d3c-b7e2-6100c732fa47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
