<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input__licensePlate</name>
   <tag></tag>
   <elementGuidId>88905eed-6284-472e-a764-db190e5b83ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputLicence']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputLicence</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>173ea7ee-8fef-4ea7-9f6c-ce4770e293a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demographic-input</value>
      <webElementGuid>a5b4bc65-3616-4abb-8ea3-a0050ff5a243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f03d85f-fa3a-46b0-ba38-44cc7561c542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputLicence</value>
      <webElementGuid>01c9bd32-e0a9-4678-807f-0ecda4170213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: ABC-1234</value>
      <webElementGuid>1b24f37a-e1b8-4d6c-b0b3-af8481e92db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>licensePlate</value>
      <webElementGuid>992ab2a6-b34b-404f-8e4b-00ee2ac88644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputLicence&quot;)</value>
      <webElementGuid>27ea61a2-a330-4a95-9f57-fcc7323c28c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputLicence']</value>
      <webElementGuid>8f5b0cf2-19db-42f8-bc54-1952d60e6aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>ffd46e18-ad84-4278-a1d3-20cdbc0bdbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>a21dc476-5ffc-4c68-a805-944fee186914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputLicence' and @placeholder = 'Example: ABC-1234' and @name = 'licensePlate']</value>
      <webElementGuid>be5b8480-bd64-4b7f-a2b1-10322f7e3059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
