<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input__makeAndModel</name>
   <tag></tag>
   <elementGuidId>bd754b2c-7177-4bd0-b800-a6793427ff8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputMakeAndModel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputMakeAndModel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fe703cc-2121-4804-aae3-31cf4cc0131a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e8e9fde-ed19-4aa5-80dc-4f1a32817885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: Toyota Camry 2016</value>
      <webElementGuid>69926000-6962-4b32-a6c7-cddf210308a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>524f3cea-9b28-40f1-9712-ba2ab316278e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputMakeAndModel</value>
      <webElementGuid>0c72826c-0821-4540-b0ad-883a6efce63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>makeAndModel</value>
      <webElementGuid>22067839-501d-4b6b-80f2-d9a178309e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputMakeAndModel&quot;)</value>
      <webElementGuid>0ac3b93e-c73d-441a-9339-bab6c7531c49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputMakeAndModel']</value>
      <webElementGuid>d4a20079-d136-4f5d-a8d9-501b0f60a916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>1328a080-10cc-4a3a-a79c-459409f81b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>2ac35a6b-de78-427b-b241-39a3e38d36ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Example: Toyota Camry 2016' and @id = 'inputMakeAndModel' and @name = 'makeAndModel']</value>
      <webElementGuid>47dda66f-ca0c-4bad-9749-b9a654111e83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
