<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_This field is required</name>
   <tag></tag>
   <elementGuidId>54b74b1a-568b-489b-aafb-475ef848f0fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container-category']/form/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4f3e75d7-fb9d-49a5-8f9c-5fe9dec4fdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>4f1e5a2e-210f-47d7-af91-8fcdc17137fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required</value>
      <webElementGuid>80bc6d00-e150-42fe-9e1c-8c1c1914e79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container-category&quot;)/form[1]/div[@class=&quot;row justify-content-between p-0&quot;]/div[@class=&quot;p-0&quot;]/span[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>2a89b122-45ef-4474-9c25-d7ee08ef7129</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container-category']/form/div/div[3]/span</value>
      <webElementGuid>e223ecda-c74c-4915-a586-0b36c09c5cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>67387976-2a2c-4842-8cce-d787fd8958fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'This field is required' or . = 'This field is required')]</value>
      <webElementGuid>95771409-7460-4c00-91b4-d8f436482ba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
