<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>8967a308-45d1-4466-9814-2201c0e59fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.requiredAstericSign</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container-category']/form/div/div/div/div/div/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3cdb8e80-7b34-4ab3-ab5b-d56cd4b5a81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>requiredAstericSign</value>
      <webElementGuid>601026ba-7ab4-4f20-a389-5d1a6be9fa95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*</value>
      <webElementGuid>8f0d8e60-2589-41dc-b71a-ce14929185c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container-category&quot;)/form[1]/div[@class=&quot;row justify-content-between p-0&quot;]/div[@class=&quot;p-0&quot;]/div[@class=&quot;col-12 p-0 my-3 border border-secondary-subtle shadow-sm rounded-bottom&quot;]/div[@class=&quot;row m-0 border border-bottom-secondary-subtle&quot;]/div[@class=&quot;col-11 p-2&quot;]/h1[@class=&quot;heading h3&quot;]/span[@class=&quot;requiredAstericSign&quot;]</value>
      <webElementGuid>647c7c3a-caaf-4da6-a542-bab528a0be9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container-category']/form/div/div/div/div/div/h1/span</value>
      <webElementGuid>69f2e147-746b-4793-ae04-8a7967696680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/h1/span</value>
      <webElementGuid>12e3a465-4fd7-4dbb-9fd3-3b01f0fbbbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '*' or . = '*')]</value>
      <webElementGuid>3e02b6d0-8524-4b12-87d2-297274a46d1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
