<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_role</name>
   <tag></tag>
   <elementGuidId>b73c1c88-9eac-4f91-a6ff-82c6528d1185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputrolecompanion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputrolecompanion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83e8aa9e-dc27-44c3-9b47-dfe213c65ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input-role </value>
      <webElementGuid>45b9cf54-22c2-4887-8ec3-2ad3b1f989ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputrolecompanion</value>
      <webElementGuid>b4f95fe4-147d-450d-afe3-f07c3776ca2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>92bcc715-f055-4e54-9649-407baaa744bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>65fd0afd-3fcc-4252-9a35-22679b19da2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Companion</value>
      <webElementGuid>9165fe03-5ae0-4597-9d41-23eb12161e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputrolecompanion&quot;)</value>
      <webElementGuid>a4429733-2ccb-47de-95e6-ec42433e7c58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputrolecompanion']</value>
      <webElementGuid>cfe1c461-b099-4c84-90bd-330b6c36c687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div[5]/div/div[2]/input</value>
      <webElementGuid>88e12eb4-0517-43b4-abea-a960ec8797e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>0b685bd5-01f5-48f9-9481-ff6a15463811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputrolecompanion' and @name = 'role' and @type = 'radio']</value>
      <webElementGuid>2913deaa-708f-4662-b0bb-780d2dd64cf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
