<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_makeAndModel</name>
   <tag></tag>
   <elementGuidId>59b47c30-c06a-4142-9484-011f8341a622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputMakeAndModel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputMakeAndModel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7986c642-586b-4d72-83a8-8b724826cf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40c8a55d-919d-4669-a759-87f0b372b65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: Toyota Camry 2016</value>
      <webElementGuid>28c7a7a1-67de-4e0e-8234-5cc87698f794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>9eda0ed1-1144-45bf-8aaa-8aab71dfe8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputMakeAndModel</value>
      <webElementGuid>ea4a5127-28d2-4bfa-b1de-d92fa196a4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>makeAndModel</value>
      <webElementGuid>32fccdcc-0cc2-4e34-bb46-898aa508ea59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputMakeAndModel&quot;)</value>
      <webElementGuid>97f961e1-02ba-4d9e-920a-edd91740616c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputMakeAndModel']</value>
      <webElementGuid>956a355e-b378-4f16-9170-22f0740a6d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>18d43875-1d15-4ceb-a9bd-853bdbba622e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>a504572e-faea-4465-83a7-2a008a15f84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Example: Toyota Camry 2016' and @id = 'inputMakeAndModel' and @name = 'makeAndModel']</value>
      <webElementGuid>53ea349f-c368-490b-82cb-061d6fb1d5a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
