<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_licensePlate</name>
   <tag></tag>
   <elementGuidId>3918ba81-71b6-4076-8438-f0160c914ed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputLicence']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputLicence</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b077274-ce28-4d45-83b7-92ceb9e65d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demographic-input</value>
      <webElementGuid>273510ff-b553-49d3-9a58-daef0e20cb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8834e98-351c-4088-98fb-390bc2a02364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputLicence</value>
      <webElementGuid>fea8bd12-a310-41ab-b995-bc5ce4d28a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: ABC-1234</value>
      <webElementGuid>de40fd77-9be0-4a01-8cc6-6650147fd8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>licensePlate</value>
      <webElementGuid>5f48dfa6-f916-4d70-9107-ef8e5f041579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputLicence&quot;)</value>
      <webElementGuid>e47bdd21-dcf1-418c-a4d6-caded87d277c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputLicence']</value>
      <webElementGuid>d4f50bcb-4217-4c59-84f6-86fc20f8de33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>6dafc48d-8db0-4e2f-ae5c-8260f1207bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>a5521b4c-63af-4293-8513-740eeef999e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputLicence' and @placeholder = 'Example: ABC-1234' and @name = 'licensePlate']</value>
      <webElementGuid>63c2946b-b279-481c-9538-1f48560c5e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
